config/routes.rb
Rails.application.routes.draw do
  get 'seller/index'
  get 'order/show'
  get 'order/destroy'
  get 'order/index'
  get 'users/show'
  get 'product/index'
  get 'product/show'
  get 'product/new'
  get 'product/edit'
  get 'dashboard/index'

  post 'product/new'
  post 'product/create'

  devise_for :users
  resources :users, :only => [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :post
  resources :product

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_action :check_signed_in

	# grab all products being sold by other users and quantity is not zero
  def index
  	@products = Product.where("UserId != ? AND Quantity != 0", current_user.id)
  end



  def check_signed_in
  	redirect_to user_session_path if !signed_in?
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

	before_action :check_signed_in

  def check_signed_in
  	redirect_to user_session_path if !signed_in?
  end

  def show
  end

  def destroy
  end

  # grab all orders from order table that has the current user id
  def index
  	@orders = Order.where(BuyerId: current_user.id)
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

	# before page load, call if_signed_in method
	before_action :if_signed_in

	# redirects a user to the login page if not logged in
	def if_signed_in
		redirect_to user_session_path if !signed_in?
	end

	# construct a query that returns all records with current user id
  def index
  	@products = Product.where("UserId = ?", current_user.id)
  end

  def show
  	@product = Product.find(params[:id])

  	@user = nil

  	if(@product.UserId != nil)
  		@user = User.find(@product.UserId)
  	end

  end


  def create
	@product = Product.new(product_params)

	# we can reference the current user who's logged in with
	# current_user.id (that's handy)
	@product[:UserId] = current_user.id

	# check if product is saved to db
	if @product.save
		redirect_to @product
	else
		render 'new'
	end

  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy

  end


  # this is used to edit a product and to purchase a product
  def update
  	
@product = Product.find(params[:id])
  	@product.update(product_params)

		if(@product.Quantity > 0 and @product != nil)
		  	@order = Order.new

		  	@order.SellerId = @product.UserId
		  	@order.BuyerId = current_user.id
		  	@order.ProductId = @product.id
		  	@order.Quantity = 1
		  	@order.Notified = false

		  	@order.save

		  	@product.Quantity = @product.Quantity - 1
		  	@product.save

		  	render 'show'
		  else 
		  	render 'show'
		 end
	
  end

  # strong params are useful for requiring and permitting certain data fields
  def product_params
  	params.require(:product).permit(:Name, :Description, :Quantity, :Price)
  end

end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
	before_action :check_signed_in

  def check_signed_in
  	redirect_to user_session_path if !signed_in?
  end

  # construct two queries -- one to determine how many new orders there are
  # and another to display all sold orders
  def index
  	@orders = Order.where("SellerId = ?", current_user.id)
  	@ordersNew = Order.where("SellerId = ? AND Notified = false", current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :check_signed_in

  def check_signed_in
  	redirect_to user_session_path if !signed_in?
  end


  def show
  	@user = User.find(params[:id])

  	@product = Product.find(@user.id)

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	before_action :check_signed_in
	def index
	end


	def check_signed_in
		redirect_to dashboard_index_path if signed_in?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<body>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>
			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">What's on the market</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>
            </div>
          </div>

<div class="album py-5 bg-light">


        <div class="container">

          <div class="row">
          		
            <div class="col-md-6">
 		<% @products.each do |f| %>
              <div class="card mb-6 box-shadow">
                
                 
				  <div class="form-row">
				  		
				    <div class="form-group col-md-6">
				      <label for="inputEmail4">Name</label>
				      <b><%= f.Name %></b>
				    </div>
				    <div class="form-group col-md-6">
				      <label for="inputPassword4">Description</label>
				      <b><%= f.Description %></b>
				    </div>

				  </div>

				  <div class="form-row">
					  <div class="form-group col-md-6">
					  	<label >Quantity</label>
					    <b><%= f.Quantity %></b>
					      
					  </div>

						<div class="form-group col-md-6">
					  	<label>Price</label>
					     <b><%= f.Price %></b>
					      
					  </div>
					  
				   </div>

                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    	<%= link_to 'View', product_path(f) %>
                    </div>
                  </div>



                </div>

                 <% end %>
              </div>


            </div>


          </div>
        </div>
      </div>

				

          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kingsmensoftware</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="/dashboard/index" class="navbar-brand d-flex align-items-center">
            <strong>Marketplace</strong>
          </a>

          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </div>



      </div>
    
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>


  </body>
</html>

app/views/order/destroy.html.erb
<h1>Order#destroy</h1>
<p>Find me in app/views/order/destroy.html.erb</p>

app/views/order/index.html.erb
<body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Product Overview</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>


            </div>
          </div>




<div class="album py-5 bg-light">


        <div class="container">

          <div class="row">
          		
            <div class="col-md-6">

            	<!--- loop through each order from the query and display its properties---> 
 		<% @orders.each do |f| %>
              <div class="card mb-6 box-shadow">
                
                 
				  <div class="form-row">
				  		
				    <div class="form-group col-md-6">
				      <label for="inputEmail4">Seller</label>
				      <b><%= f.SellerId %></b>
				    </div>
				    <div class="form-group col-md-6">
				      <b><%= link_to 'View Product', product_path(Product.find(f.ProductId)) %></b>
				    </div>

				  </div>

				  <div class="form-row">
					  <div class="form-group col-md-6">
					  	<label >Quantity</label>
					    <b><%= f.Quantity%></b>
					      
					  </div>

						<div class="form-group col-md-6">
					  	<label>Price</label>
					     <b><%= Product.find(f.ProductId).Price %></b>
					      
					  </div>
					  
				   </div>

                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                    
                    </div>
                  </div>



                </div>

                 <% end %>
              </div>


            </div>


          </div>
        </div>
          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
    </div>

  </body>

app/views/order/show.html.erb
<h1>Order#show</h1>
<p>Find me in app/views/order/show.html.erb</p>

app/views/product/edit.html.erb
<body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Product Edit</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>
            </div>
          </div>

          <!--- create form for product and send the form to the new action --->
          <%= form_for @product do |f| %>

				  <div class="form-row">
				  		
				    <div class="form-group col-md-6">
				      <label for="inputEmail4">Product Name</label>
				      <%= f.text_field :Name %>
				    </div>
				    <div class="form-group col-md-6">
				      <label for="inputPassword4">Product Description</label>
				      <%= f.text_field :Description %>
				    </div>

				  </div>
				  <div class="form-row">
					  <div class="form-group col-md-6">
					  	<label >Quantity</label>
					    <%= f.number_field :Quantity, :class => 'text_field' %>
					      
					  </div>

						<div class="form-group col-md-6">
					  	<label>Price</label>
					    <%= f.number_field :Price, class: :text_field, step: :any %>
					      
					  </div>
					  
				</div>
				  
				  <%= f.submit %>
			<% end %>		


          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
    </div>

  </body>

app/views/product/index.html.erb
<body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Product Overview</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>
            </div>
          </div>
          <table>
          	<tr>
          		<th>Name<th>
          		<th>Description<th>
          		<th>Edit</th>
          	</tr>
          <% @products.each do |f| %>
          		<tr>
          			<td><%= f.Name %></td>
          			<td><%= f.Description %></td>
          			<td><%= link_to 'Edit', edit_product_path(f) %></td>
          			<td><%= link_to 'Delete', f, method: :delete, data: { confirm: 'Are you sure?'} %> </td>
          		<tr>
          <% end %>
      		</table>
      		<%= link_to 'Add new product', '/product/new' %>
          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
    </div>

  </body>

app/views/product/new.html.erb
<body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Product Add</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>
            </div>
          </div>

          <%= form_for(:product, :url => {:action => 'create'}) do |f| %>

				  <div class="form-row">
				  		
				    <div class="form-group col-md-6">
				      <label for="inputEmail4">Product Name</label>
				      <%= f.text_field :Name %>
				    </div>
				    <div class="form-group col-md-6">
				      <label for="inputPassword4">Product Description</label>
				      <%= f.text_field :Description %>
				    </div>

				  </div>
				  <div class="form-row">
					  <div class="form-group col-md-6">
					  	<label >Quantity</label>
					    <%= f.number_field :Quantity, :class => 'text_field' %>
					      
					  </div>

						<div class="form-group col-md-6">
					  	<label>Price</label>
					    <%= f.number_field :Price, class: :text_field, step: :any %>
					      
					  </div>
					  
				</div>
				  <%= f.submit %>
			<% end %>		
          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
    </div>

  </body>

app/views/product/show.html.erb
<body>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>
			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Product Show</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>
            </div>
          </div>

          <%= form_for(@product, :url => {:action => 'update'}) do |f| %>

				  <div class="form-row">
				  		
				    <div class="form-group col-md-6">
				      <label for="inputEmail4">Name</label>
				      <b><%= @product.Name %></b>
				    </div>
				    <div class="form-group col-md-6">
				      <label for="inputPassword4">Description</label>
				      <b><%= @product.Description %></b>
				    </div>

				  </div>
				  <div class="form-row">
					  <div class="form-group col-md-6">
					  	<label >Quantity</label>
					    <b><%= @product.Quantity %></b>
					      
					  </div>

						<div class="form-group col-md-6">
					  	<label>Price</label>
					     <b><%= @product.Price %></b>
					      
					  </div>
					  
				</div>
				<%= link_to "Seller profile", user_path(@user) if @user != nil %>
				<%= f.submit "Buy product" if @product.Quantity > 0%>
			<% end %>		
          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
  </div>
</body>

app/views/seller/index.html.erb
<body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Seller Overview</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>
            </div>
          </div>


          <div class="album py-5 bg-light">


        <div class="container">

          <div class="row">
          		
            <div class="col-md-6">
 				<b>New Orders: <%= @ordersNew.size %></b>
 				<% @orders.each do |f| %>
              <div class="card mb-6 box-shadow">
                
                 
				  <div class="form-row">

				    <div class="form-group col-md-6">
				      <b><%= link_to 'View Buyer\'s Profile', user_path(Order.find(f.BuyerId)) %></b>
				    </div>

				  </div>

				  <div class="form-row">
					  <div class="form-group col-md-6">
					  	<label >Quantity</label>
					    <b><%= f.Quantity%></b>
					      
					  </div>

					  </div>
					  
				   </div>

                </div>
                	
                	<!--- <%= f.Notified = true %>
                	<%= f.save %> --->
              
                 <% end %>
              </div>


            </div>


          </div>
        </div>



          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
    </div>

  </body>

app/views/users/show.html.erb
<body>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
                            <li class="nav-item">
                <%= link_to 'Dashboard', "/dashboard/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Orders', "/order/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Products', "/product/index" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Seller Panel', "/seller/index" %>
              </li>
            </ul>

          </div>
        </nav>
			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">Product Show</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                
              </div>
            </div>
          </div>
				<div class="form-row">

				  <div class="form-group col-md-6">
				      <label for="inputEmail4">Email</label>
				      <b><%= @user.email %></b>
				 </div>
          <%= form_for(@product) do |f| %>

				  

				    <div class="form-group col-md-6">
				      <label for="inputPassword4">Product</label>
				      <b><%= @product.Description %></b>
				    </div>

				  </div>
				  <div class="form-row">
					  <div class="form-group col-md-6">
					  	<label >Quantity</label>
					    <b><%= @product.Quantity %></b>
					      
					  </div>

						<div class="form-group col-md-6">
					  	<label>Price</label>
					     <b><%= @product.Price %></b>
					      
					  </div>
					  
				</div>
			<% end %>		
          <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

        </main>
      </div>
  </div>
</body>

app/views/welcome/index.html.erb
<body>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Kingsmen's marketplace</h1>
          <p class="lead text-muted">Need a market to sell your personal items quick and cheap? Look no longer!</p>
          <p>
            <a href="#" class="btn btn-primary my-2">Signup</a>
          </p>
        </div>
      </section>

    </main>

    <footer class="text-muted">

    </footer>
</body>